Implement Duplicate Finder
Difegue/LANraragi pull request #1107
Opened 2024-11-01 17:37 UTC by dix0nym

Implement a feature to detect and delete duplicate archives in the library based on the hamming distance between thumbnail hashes (https://github.com/Difegue/LANraragi/issues/338).

The minion job is parallelized and is way faster than the initial plugin, for my library (27k archives, 730GB) a full run took about 1h.
Additionally, I improved upon the script instead of only return duplicate pairs (e.g. we have 3 duplicate archives: id1 -> id2, id1 -> id3, id1 -> id3, now it returns one group [id1, id2, id3]).

view in `/duplicates`,  it is currently not connected from anywhere else. Should be considered if it should be linked to from navbar or settings. Furthermore, the CSS is defined inline in the HTML, maybe it should be separated into separate file?

![view-duplicates](https://github.com/user-attachments/assets/49fb0bed-e9e9-4db8-9bcd-5f6e1d094fd1)

I could not figure out how to do the tooltip for the tags like it is on index page. Would be great to see the actual tags if you hover over the tag count. I would need some help there.

I implemented different ways to delete the duplicates:
- manual - one by one
- selecting based on attribute
  - tag count
  - file size
  - page count
  - date

![select](https://github.com/user-attachments/assets/04766411-cd8f-4935-8261-87f58895675b)

Tested on my library, detected and deleted 776 duplicate groups.

Would appreciate any feedback.

2024-11-04 00:26 UTC, Difegue requested changes
Thanks a lot for this! Looks delightful.  

I'll give this a more indepth review later, but I don't think the API should have any "batch" kind of endpoints if possible - Single/Atomic operations are easier to code on the server-side and clients can just loop a bunch of calls..  

If the toasts are annoying I believe it'd be useful to add an optional parameter to the JS function for API calls to disable showing them on a successful operation.

2024-12-31 06:04 UTC, chu-shen commented
Please add ignore option to the archive. For example, if you want to preserve duplicate archives with different translation styles.

2025-01-31 00:03 UTC, Difegue commented on public/js/server.js
> +            $(".find-duplicates").prop("disabled", true);
I think it'd also be good to feature a spinner of some form in the UI to indicate the job is in progress.  

Now of course that all kinda goes away if the user reloads the page while the job is running -- I wonder if we shouldn't store the minion job ID somewhere so it can be detected on a reload. (Either on the controller side with the database, or just with localstorage? Controller is probably better but that'd be a bit annoying with the generic API call)

2025-01-31 00:06 UTC, Difegue commented on public/js/server.js
> +                        text: d.result.errors,
I don't think the duplicate job can return errors, right?

2025-01-31 00:17 UTC, Difegue commented on public/js/duplicates.js
> +                    Server.deleteArchive(dataId, () => { Duplicates.dt.row(row).remove().draw() });
As mentioned in the previous comments, it'd be fine to add an optional boolean to `deleteArchive` to make it not emit the success toast.  

(The success toast doesn't really makes sense here as well since it doesn't actually reload the page, too)

2025-01-31 00:24 UTC, Difegue commented on templates/duplicates.html.tt2
> +                            </td>
If you want the tags tooltip to work, I think you could do something like this:  
```suggestion
                            <td class="tag-count tag-tooltip" onmouseover="IndexTable.buildTagTooltip(this)" >
                                <i class="fa-solid fa-tag"></i>
                                [% archive.tags.split(",").size %]
                            </td>
                            <div class="caption caption-tags" style="display: none;" >
                                    ${LRR.buildTagsDiv("[% archive.tags %]")}
                            </div>
```

2025-01-31 00:28 UTC, Difegue commented on templates/duplicates.html.tt2
> +	<script src="[% c.url_for("/js/vendor/jqcloud.min.js") %]"></script>
Don't think jqcloud and allcollapsible are used here

2025-01-31 00:32 UTC, Difegue commented on templates/duplicates.html.tt2
> +        <p>Found [% duplicates.size %] duplicate groups</p>
There should be some explanatory text here that details how the feature works. 

("Found X duplicate groups" might be good to hide if there's no duplicate results? Not necessary though imo)

2025-01-31 00:33 UTC, Difegue commented on templates/duplicates.html.tt2
> +            <div class="select-btn-group">
I'd hide this div if there are no duplicate groups found/available.

2025-01-31 00:40 UTC, Difegue commented on templates/duplicates.html.tt2
> +                                </div>
I'd use the same tooltip mechanism as the main index here instead:  

```suggestion
                                <div class="thumbnail-wrapper">
                                    <a onmouseover="IndexTable.buildImageTooltip(this)" href="${new LRR.apiURL('/reader?id=[% archive.arcid %]')}" title="[% archive.title %]">
                                        <img class="thumbnail" src="${new LRR.apiURL(`/api/archives/[% archive.arcid %]/thumbnail`)}" width="100"/>
                                    </a>
                                    <div class="caption" style="display: none;">
                                        <img style="height:300px" src="${new LRR.apiURL('/api/archives/${data.arcid}/thumbnail')}" 
                                                  onerror="this.src='${new LRR.apiURL('/img/noThumb.png')}'">
                                    </div>
                                </div>
```

2025-01-31 00:50 UTC, Difegue commented on lib/LANraragi/Utils/Minion.pm
> +                            next if $visited{$id};
Since you've used `split_workload_by_cpu`, normally each process/thread should have its own unique set of IDs.  

I'm not sure you need visited as a result?

2025-01-31 00:55 UTC, Difegue commented on templates/duplicates.html.tt2
> +    <style>
Yeah I'm not a fan of having special CSS here, this will mess up custom themes.  
Ideally I think everything here is doable with the base lrr.css and re-using Index bits for the tags and thumbnail popups.  

It's fine to add a few extra classes to lrr.css if you'd need specific sizing.

2025-02-19 11:21 UTC, psilabs-dev commented
Thanks for working on this problem!

I notice there's one new post API in routing. Is this fire and forget/browserless? I'd like to call the job via curl/API client, let it run on a handful of cpus, then collect the results after a couple days.

In my case I'm hesitant to delete based on thumbnail similarity alone, but this feature would be a great starting point for further duplicate analysis based on custom user logic and code. E.g., merge tags among dupes, adding dupe sources to kept archives, prioritizing archives with most likes/bookmarks (if supported) or based on existing sort namespace, keeping different translations, setting do-not-downloads, etc.

This is also a comment long past implementation, so I understand if it's out of scope now.

2025-02-19 23:30 UTC, Difegue commented
The dupe scan job is just a minion task, so you can just fire and forget it, yeah.  
I'll wrap up the PR myself eventually if the original writer doesn't come back - that's what I get for having taken 3 months to review it...

2025-02-20 21:26 UTC, Difegue commented
Oh, thanks! Feel free to take your time, I'm in no rush.

2025-02-21 06:43 UTC, psilabs-dev commented
> The current approach is the simplest and most lightweight beside simple hash comparison, but I’m curious - how would you envision integrating _custom_ user logic and code? Would this be through additional filters and sorting options, or are you thinking of a deeper integration, some kind of plugin support?

It depends on the data source/plugin. For a site like Pixiv, the idea of "duplicate" doesn't *really* exist. Nhentai, on the other hand, has tons of true duplicates. Same manga, different translations; same translation, different translators; same series continuation, different to-be-continued chapters... Perhaps metadata plugins may be extended, e.g. nhentai-deduplication, e-hentai-deduplication, etc.

It would be difficult to incorporate all custom user logic, because different users have different definitions of what it means for two archives to be similar. It's better to keep two archives that may be duplicates than it is to delete a unique archive. So hands-off archive deletion of potentially tens of thousands of archives is not an easy ask.

The straighforward option is to offer an API interface, and let the users write their own duplicate detection in their language of choice. One API to trigger duplicate archive scanning, another to collect the results.

For example, trigger a scan on some endpoint:
```sh
curl -X POST http://localhost:3000/api/duplicates?cpus=4
# {"job_id": 123, "status": "success", "message": "Thumbnail duplicate scanning minion job queued!"}
```
then collect scan results:
```sh
curl -X GET http://localhost:3000/api/duplicates/123
```
return payload as list of similar archives by ID:
```json
{
    "status": "success/in-progress/failed",
    "data/duplicate archive IDs": [
        ["abcd", "efgh"],
        ["ijkl", "mnop", "qrst"]
    ]
}
```
I also wonder if we can extract the "image similarity" method so we can choose methods besides levenshtein distance in the future...

To give a practical example: I have a number of tagged archives downloaded via nhentai-archivist and cleaned with an internal service. LRR has RO access to contents downloaded by archivist so it cannot delete archives. This is what I'd be eventually doing (on a privileged service).

1. collect results of the duplicate scans
3. categorize archives within each cluster by "language:\*" tag
4. within a specific bucket, perform page-by-page image similarity checks: if an archive is a subset of another archive to a large extent (e.g. 80%-100% contained): the smaller archive can be deleted without much loss of information. Otherwise, they are not sufficiently similar. Then break these buckets down to page content-specific buckets
5. rank archives in these buckets by number of favorites, whether they have the "uncensored" tag or another indication of quality tag, whether they are in-progress, or whether they are in a static category. Basically find the "best quality" archive. Keep the archive with the highest ranking, queue deletion of the rest, and add some kind of "duplicate_source" tag for this kept archive pointing to the sources of deleted archives.
6. add the deleted archives to the nhentai-archivist do-not-delete catalog, then validate/execute deletion of archives

then add some basic logging, notifications, and run this once a month or something with a cron-job. Of course what I'm doing is subjective to my setup.

2025-03-17 08:20 UTC, psilabs-dev commented
Just an update on this; I decided to go the route of deduplication by treating archives as sequences of images, and solving the problem by finding all sequences which are proper subsequences of another sequence. In this case, equality between images is replaced with sufficient similarity between resnet embeddings. Equal-length duplicate sequences are handled by an nhentai-specific metadata comparison algorithm to determine which archive to keep.

The job is taking a super-long time (attempt to multiproc caused race conditions I was too lazy/dumb to fix :p), but around 16-17% of archives are projected to be duplicates (which after checking, indeed they are) which is good enough for me since that would shave off a considerable number of gbs from my disk, so I'm just letting it run while I go on with my day

2025-03-30 23:08 UTC, closed without merging