Add nHentai-Plugin to bypass CF JS-Challenge
Difegue/LANraragi pull request #633
Opened 2022-05-25 17:04 UTC by Pheromir

Added a new plugin to pass cookies and a useragent to LRR to bypass the Cloudflare JavaScript-Challenge.
I specifially named it like that (instead of "nHentai Login" or something like that) so it doesn't get confused with an actual login to the website.

The login plugin is based on the login-example from the documentation and your ehlogin.
for the Metadata-Plugin I changed the author to "Difegue and others" as it is the same way in the E-Hentai Metadata Plugin as an example.

I hope everything's fine, but you might check twice to be sure, as it's the first time I used pearl.

Tested one archive by providing a URL (see screenshot) and one archive by uploading it with the gID in the name ("{id} name") - both worked.

![firefox_2022-05-25-18-45-10](https://user-images.githubusercontent.com/13359741/170320036-691202f4-3a95-4224-9d23-57049c446a5c.png)

2022-05-25 17:05 UTC, Pheromir commented
(this should close #631)

2022-05-26 00:38 UTC, Difegue requested changes
Thank you very much for having taken the time to research this; Code-wise everything looks fine, I only have a few nitpicks on wording for the plugin's user-facing instructions. ✌️

2022-05-26 00:38 UTC, Difegue commented on lib/LANraragi/Plugin/Login/nHentai.pm
> +			{ type => "string", desc => "cf_clearance cookie of domain .nhentai.net" }
```suggestion
			{ type => "string", desc => "cf_clearance cookie for domain nhentai.net" }
```

2022-05-26 00:38 UTC, Difegue commented on lib/LANraragi/Plugin/Login/nHentai.pm
> +			{ type => "string", desc => "csrftoken cookie of domain nhentai.net" },
```suggestion
			{ type => "string", desc => "csrftoken cookie for domain nhentai.net" },
```

2022-05-26 00:38 UTC, Difegue commented on lib/LANraragi/Plugin/Login/nHentai.pm
> +            { type => "string", desc => "user-agent" },
```suggestion
              { type => "string", desc => "Browser UserAgent string (Can be found at http://useragentstring.com/ for your browser)" },
```

2022-05-26 09:15 UTC, Pheromir commented
> Code-wise everything looks fine

Nice.

> I only have a few nitpicks on wording for the plugin's user-facing instructions. ✌️

I kinda thought that would happen, I wasn't sure if the description would have been too long or something like that (except for the of/for mistake). I applied your suggestions. (Writing that because I don't know if you've gotten any notification about it, as the webhook in the discord channel didn't post anything, lol)

2022-05-26 21:07 UTC, merged

2022-05-27 06:30 UTC, Andor233 commented
Thanks! It works fine for me.