Add category message
Difegue/LANraragi pull request #780
Opened 2023-03-17 23:06 UTC by siliconfeces

This PR makes the toast after adding an archive to a category more helpful.
Before:
![image](https://user-images.githubusercontent.com/124937394/226067042-58b21a4a-27a2-4dd8-bd76-410c6136c659.png)
After:
![image](https://user-images.githubusercontent.com/124937394/226066947-7a370d2c-ed25-4631-b81c-fa140ff7ba8a.png)

More interestingly, it also adds support for backend code (aka perl) to return the success message that appears in toasts.

2023-03-17 23:58 UTC, Difegue requested changes
Looks good at a glance -- Could you edit the example API response in the [Docs](https://github.com/Difegue/LANraragi/blob/dev/tools/Documentation/api-documentation/category-api.md) as well? Thanks!

2023-03-18 00:13 UTC, siliconfeces commented
> Looks good at a glance -- Could you edit the example API response in the [Docs](https://github.com/Difegue/LANraragi/blob/dev/tools/Documentation/api-documentation/category-api.md) as well? Thanks!

Done, but not sure how to check what the rendered documentation looks like so I might have fucked something up.

2023-03-18 23:15 UTC, Difegue approved these changes

2023-03-18 23:16 UTC, Difegue commented
Well, there's no way for me either to know how the doc will look like 'til it lands in dev or master since that's on GitBook's hands, but I'm fairly sure it'll look fine like this.  

Mergin' this 👍

2023-03-18 23:17 UTC, merged