Add OPDS-PS1 1.2 support for lastReadDate
Difegue/LANraragi pull request #791
Opened 2023-04-16 23:13 UTC by kuroneko995

This address https://github.com/Difegue/LANraragi/issues/773 by adding lastReadDate support to the OPDS API endpoints. If server side progress is enabled, lastReadDate is saved whenever progress is updated. OPDS API request will include the lastReadDate field if it's available.

This does not add support for the main LRR app, for example:
- lastReadDate is not rendered in the UI
- lastReadDate is not supported in queries
- Documentation has not been updated

2023-04-17 15:15 UTC, Difegue requested changes
This looks perfect, thanks!  

The only request I'd have is that it'd be great if you could add `lastReadDate` to the test for OPDS: It should just be a matter of adding some `lastreadtime` values in the database mocks here: https://github.com/Difegue/LANraragi/blob/dev/tests/mocks.pl 
and then modifying the test output sample here so it matches: https://github.com/Difegue/LANraragi/blob/dev/tests/samples/opds/opds_sample.xml  .

2023-04-18 03:21 UTC, kuroneko995 commented
I've update the test as requested. Please take another look.

2023-04-18 21:02 UTC, Difegue approved these changes

2023-04-18 21:03 UTC, merged

2023-04-18 21:03 UTC, Difegue commented
Perfect, thanks once again! 

@holopin-bot @kuroneko995